# fly.toml app configuration file generated for periodo-legacy-subdomain on 2023-09-14T20:02:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "periodo-legacy-subdomain"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
